const DB_NAME = 'football-film-log', STORE_NAME = 'folder-handle', HANDLE_KEY = 'project-folder'
let folderHandle = null
function supported() { return typeof window !== 'undefined' && 'showDirectoryPicker' in window }
function openDb() { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE_NAME); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) }) }
async function getStoredHandle() { const db = await openDb(); return new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME, 'readonly').objectStore(STORE_NAME).get(HANDLE_KEY); request.onsuccess = () => resolve(request.result || null); request.onerror = () => reject(request.error) }) }
async function storeHandle(handle) { const db = await openDb(); return new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME, 'readwrite').objectStore(STORE_NAME).put(handle, HANDLE_KEY); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error) }) }
async function statusFor(handle) { if (!supported()) return { state: 'unsupported', message: 'Film Log needs a Chromium browser with File System Access support.' }; if (!handle) return { state: 'disconnected', message: 'Connect the Football project folder to save Film Log files.' }; const permission = await handle.queryPermission({ mode: 'readwrite' }); return permission === 'granted' ? { state: 'connected', message: 'Film Log is saving to the connected project folder.' } : { state: 'reconnect', message: 'Reconnect film-log folder to save this draft.' } }
async function requireFolder() { const status = await getConnectionStatus(); if (status.state !== 'connected') throw new Error(status.message); return folderHandle }
async function directory(handle, name) { return handle.getDirectoryHandle(name, { create: true }) }
async function writeJson(handle, name, value) { const file = await handle.getFileHandle(name, { create: true }), stream = await file.createWritable(); await stream.write(JSON.stringify(value, null, 2)); await stream.close() }
async function readJson(handle, name) { const file = await (await handle.getFileHandle(name)).getFile(); return JSON.parse(await file.text()) }
function imageExtension(blob) { const type = blob.type.split('/')[1]; return type === 'jpeg' ? 'jpg' : type === 'png' || type === 'webp' || type === 'gif' ? type : 'png' }
async function thumbnail(blob) { const image = await createImageBitmap(blob), width = Math.min(200, image.width), height = Math.max(1, Math.round(image.height * width / image.width)), canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; canvas.getContext('2d').drawImage(image, 0, 0, width, height); image.close(); return new Promise((resolve) => canvas.toBlob((result) => resolve(result), 'image/jpeg', .82)) }

export async function getConnectionStatus() { try { if (!folderHandle && supported()) folderHandle = await getStoredHandle(); return await statusFor(folderHandle) } catch { return { state: 'disconnected', message: 'Connect the Football project folder to save Film Log files.' } } }
export async function connectFolder() { if (!supported()) return getConnectionStatus(); if (!folderHandle) folderHandle = await getStoredHandle(); if (folderHandle) { const permission = await folderHandle.requestPermission({ mode: 'readwrite' }); if (permission === 'granted') return statusFor(folderHandle) } folderHandle = await window.showDirectoryPicker({ mode: 'readwrite' }); await storeHandle(folderHandle); return statusFor(folderHandle) }
// Sessions are one JSON file each so agents can read a complete session and its nested entries in one file.
export async function createSession(session) { const root = await requireFolder(), sessions = await directory(await directory(root, 'film-log'), 'sessions'), value = { ...session, entries: session.entries || [] }; await writeJson(sessions, `${value.id}.json`, value); return value }
export async function addEntry(sessionId, entry) { const root = await requireFolder(), sessions = await directory(await directory(root, 'film-log'), 'sessions'), session = await readJson(sessions, `${sessionId}.json`), next = { ...session, entries: [entry, ...(session.entries || [])] }; await writeJson(sessions, `${sessionId}.json`, next); return next }
export async function updateEntry(sessionId, entryId, patch) { const root = await requireFolder(), sessions = await directory(await directory(root, 'film-log'), 'sessions'), session = await readJson(sessions, `${sessionId}.json`), entries = (session.entries || []).map((entry) => entry.id === entryId ? { ...entry, ...patch } : entry), next = { ...session, entries }; await writeJson(sessions, `${sessionId}.json`, next); return next }
export async function listSessions() { const root = await requireFolder(), sessions = await directory(await directory(root, 'film-log'), 'sessions'), list = []; for await (const [name, handle] of sessions.entries()) if (handle.kind === 'file' && name.endsWith('.json')) list.push(await readJson(sessions, name)); return list.sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt))) }
export async function listEntries(sessionId) { const root = await requireFolder(), sessions = await directory(await directory(root, 'film-log'), 'sessions'), session = await readJson(sessions, `${sessionId}.json`); return [...(session.entries || [])] }
export async function saveScreenshot(blob) { const root = await requireFolder(), screenshots = await directory(await directory(root, 'film-log'), 'screenshots'), id = crypto.randomUUID(), extension = imageExtension(blob), filename = `${id}.${extension}`, thumbnailFilename = `${id}-thumb.jpg`, thumb = await thumbnail(blob); for (const [name, value] of [[filename, blob], [thumbnailFilename, thumb]]) { const file = await screenshots.getFileHandle(name, { create: true }), stream = await file.createWritable(); await stream.write(value); await stream.close() } return { filename, thumbnailFilename } }
export async function readScreenshot(filename) { const root = await requireFolder(), screenshots = await directory(await directory(root, 'film-log'), 'screenshots'); return (await (await screenshots.getFileHandle(filename)).getFile()) }
