import { useEffect, useMemo, useState } from 'react'
import { getConnectionStatus, listSessions, readScreenshot } from '../lib/filmLogStorage'
import './filmLogLibrary.css'

function Screenshot({ screenshot }) { const [url, setUrl] = useState(''); useEffect(() => { let active = true, objectUrl = ''; readScreenshot(screenshot.thumbnailFilename || screenshot.thumbnail).then((file) => { objectUrl = URL.createObjectURL(file); if (active) setUrl(objectUrl); else URL.revokeObjectURL(objectUrl) }).catch(() => {}); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl) } }, [screenshot.thumbnailFilename, screenshot.thumbnail]); return url ? <img className="library__thumb" src={url} alt="Attached film screenshot" /> : null }
function sessionLabel(session) { return session.subject === 'opponent' ? `vs ${session.opponentName || 'Opponent'}` : `Self · ${session.context || 'Film'}` }
function resultSessionLabel(session) { return [session.week || 'No week set', session.subject === 'opponent' ? `vs ${session.opponentName || 'Opponent'}` : `Self · ${session.context || 'Film'}`, session.filmDate].filter(Boolean).join(' · ') }

export default function FilmLogLibrary() {
  const [status, setStatus] = useState({ state: 'loading', message: 'Checking Film Log folder…' }), [sessions, setSessions] = useState([]), [expanded, setExpanded] = useState(() => new Set()), [expandedSession, setExpandedSession] = useState(() => new Set()), [query, setQuery] = useState(''), [search, setSearch] = useState({ loading: false, results: [], error: '', searched: false })
  const connected = status.state === 'connected'
  useEffect(() => { let active = true; const load = async () => { const nextStatus = await getConnectionStatus(); if (!active) return; setStatus(nextStatus); if (nextStatus.state === 'connected') { try { const saved = await listSessions(); if (active) setSessions(saved) } catch (error) { if (active) setStatus({ state: 'disconnected', message: error.message || 'Could not read Film Log sessions.' }) } } }; load(); return () => { active = false } }, [])
  const groups = useMemo(() => { const byWeek = new Map(); for (const session of sessions) { const week = session.week?.trim() || 'No week set'; if (!byWeek.has(week)) byWeek.set(week, []); byWeek.get(week).push(session) } return [...byWeek.entries()].sort(([a], [b]) => { if (a === 'No week set') return 1; if (b === 'No week set') return -1; return a.localeCompare(b, undefined, { numeric: true }) }) }, [sessions])
  const toggle = (setValue, key) => setValue((previous) => { const next = new Set(previous); if (next.has(key)) next.delete(key); else next.add(key); return next })
  const runSearch = async (event) => { event.preventDefault(); const value = query.trim(); if (!value) return; setSearch({ loading: true, results: [], error: '', searched: true }); try { const response = await fetch('http://127.0.0.1:5199/search-notes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query: value }) }), payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Could not search Film Log notes.'); setSearch({ loading: false, results: payload.results || [], error: '', searched: true }) } catch (error) { const bridgeOffline = error instanceof TypeError || /failed to fetch|networkerror/i.test(error.message); setSearch({ loading: false, results: [], error: bridgeOffline ? "Analysis bridge isn't running -- start it with `npm run dev`." : error.message || 'Could not search Film Log notes.', searched: true }) } }
  return <div className="library">
    <div className={`library__connection library__connection--${status.state}`} role={connected ? 'status' : 'alert'}>{status.message}</div>
    <section className="library__panel library__search"><div className="library__panel-heading"><span>Find similar notes</span><small>Search every logged Film Log session with a plain-language question.</small></div><form className="library__search-form" onSubmit={runSearch}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="e.g. opponent tendencies against pressure" /><button type="submit" className="library__primary-btn" disabled={search.loading || !query.trim()}>{search.loading ? 'Searching notes…' : 'Find similar notes'}</button></form>{search.loading && <p className="library__search-loading" role="status"><span className="library__spinner" aria-hidden="true" />Searching every logged note. This can take 30–90 seconds.</p>}{search.error && <p className="library__search-error" role="alert">{search.error}</p>}{search.searched && !search.loading && !search.error && search.results.length === 0 && <p className="library__empty">No relevant notes found.</p>}{search.results.map((result) => <article className="library__result" key={result.entryId}><div className="library__result-heading"><span>{resultSessionLabel(result.session)}</span><small>{result.reason}</small></div><div className="library__result-entry">{result.entry.screenshots?.[0] && <Screenshot screenshot={result.entry.screenshots[0]} />}<div>{result.entry.unit && <i>{result.entry.unit}</i>}{result.entry.playNameSnapshot && <b>{result.entry.playNameSnapshot}</b>}<p>{result.entry.body}</p>{result.entry.tags?.length > 0 && <div className="library__tags">{result.entry.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>}</div></div></article>)}</section>
    <section className="library__sessions"><div className="library__panel-heading"><span>Film Log library</span><small>{connected ? `${sessions.length} saved ${sessions.length === 1 ? 'session' : 'sessions'}, organized by week.` : 'Connect the Football project folder in Film Log to browse saved sessions.'}</small></div>{connected && groups.length === 0 && <p className="library__empty">No saved Film Log sessions yet.</p>}{groups.map(([week, weekSessions]) => { const isOpen = expanded.has(week); return <div className={`library__week${isOpen ? ' is-open' : ''}`} key={week}><button type="button" className="library__week-header" aria-expanded={isOpen} onClick={() => toggle(setExpanded, week)}><svg className="library__week-caret" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true"><path d="M3 1.5 7 5 3 8.5" fill="none" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" /></svg><span>{week}</span><small>{weekSessions.length}</small></button>{isOpen && <div className="library__week-sessions">{weekSessions.map((session) => { const sessionOpen = expandedSession.has(session.id); return <div className={`library__session${sessionOpen ? ' is-open' : ''}`} key={session.id}><button type="button" className="library__session-header" aria-expanded={sessionOpen} onClick={() => toggle(setExpandedSession, session.id)}><div><b>{sessionLabel(session)}</b><span>{session.filmDate || 'No film date'}</span></div><small>{session.entries?.length || 0} {session.entries?.length === 1 ? 'note' : 'notes'}</small></button>{sessionOpen && <div className="library__entries">{(session.entries || []).length === 0 ? <p className="library__empty">No notes in this session.</p> : (session.entries || []).map((entry) => <article className="library__entry" key={entry.id}>{entry.screenshots?.[0] && <Screenshot screenshot={entry.screenshots[0]} />}<div><div className="library__entry-meta"><i>{entry.unit || 'self'}</i><small>{entry.playNameSnapshot || 'not matched'}</small></div><p>{entry.body}</p>{entry.tags?.length > 0 && <div className="library__tags">{entry.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>}</div></article>)}</div>}</div> })}</div>}</div> })}</section>
  </div>
}
