import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { getStroke } from 'perfect-freehand'
import './playbookTrainer.css'
import seed from '../data/playbook-trainer-seed.json'

const STORAGE_KEY = 'playbook-trainer-deck-v1'
const CATEGORIES = [{ value: 'all', label: 'All' }, { value: 'formation', label: 'Formations' }, { value: 'concept', label: 'Pass Concepts' }, { value: 'fullfield', label: 'Full-Field' }]
const CATEGORY_SELECT_OPTIONS = [{ value: 'formation', label: 'Formation' }, { value: 'concept', label: 'Pass Concept' }, { value: 'fullfield', label: 'Full-Field' }]
const SIDE_OPTIONS = [{ value: '', label: 'None' }, { value: 'left', label: 'Left' }, { value: 'right', label: 'Right' }]
const CANVAS_W = 480, BOARD_W = 580, CANVAS_H = 300, SNAP_DISTANCE = 14
const BASE_BUBBLES = [
  ['QB', 240, 188], ['OL_LT', 176, 150], ['OL_LG', 208, 150], ['OL_RG', 272, 150], ['OL_RT', 304, 150],
].map(([type, x, y]) => ({ id: type.toLowerCase(), type, x, y }))
const SKILL_TRAY = [['X', 520, 56], ['H', 520, 112], ['Y', 520, 168], ['Z', 520, 224]]

function loadDeck() { try { const raw = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null'); if (Array.isArray(raw)) return raw } catch {} return structuredClone(seed) }
function saveDeck(deck) { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(deck)) } catch { window.alert('Could not save -- storage is full or unavailable. This change was NOT saved. Delete an old diagram to free space, then try again.') } }
function blankSession() { return { attempts: 0, correct: 0, streak: 0, best: 0 } }
function weightedPick(pool, excludeId) { const candidates = pool.length > 2 ? pool.filter((c) => c.id !== excludeId) : pool; const list = candidates.length ? candidates : pool; let roll = Math.random() * list.reduce((sum, c) => sum + (6 - c.box), 0); for (const c of list) { roll -= 6 - c.box; if (roll <= 0) return c } return list.at(-1) }
function buildPrompt(name, variation, side) { const suffix = variation || (side === 'left' ? 'L' : side === 'right' ? 'R' : null); return suffix ? `${name} — ${suffix}` : name }
const humanizeSide = (side) => (side === 'left' ? 'Left' : side === 'right' ? 'Right' : null)
function tagsFor(card) { return [humanizeSide(card.side), card.variation].filter(Boolean) }
function createDiagram() { return { bubbles: [...BASE_BUBBLES, ...SKILL_TRAY.map(([type, x, y]) => ({ id: type.toLowerCase(), type, x, y }))], lines: [] } }
function normalDiagram(diagram) { return diagram && typeof diagram === 'object' ? diagram : null }
function pathFromStroke(points) { if (!points.length) return ''; const d = points.reduce((path, p, i) => `${path}${i ? ' L' : 'M'}${p[0].toFixed(1)},${p[1].toFixed(1)}`, ''); return `${d} Z` }
function strokePath(points) { return pathFromStroke(getStroke(points.map((p) => [p.x, p.y, 0.5]), { size: 3.4, smoothing: 0.65, streamline: 0.45, thinning: 0 })) }

function useDrillCard(pool) { const [currentId, setCurrentId] = useState(null); const poolRef = useRef(pool); useEffect(() => { poolRef.current = pool }); const advance = useCallback((excludeId) => { const p = poolRef.current; setCurrentId(p.length ? weightedPick(p, excludeId).id : null) }, []); const poolIds = pool.map((c) => c.id).join(','); useEffect(() => { if (!pool.length) { setCurrentId(null); return } if (!pool.some((c) => c.id === currentId)) advance(currentId) }, [poolIds]); return { current: pool.find((c) => c.id === currentId) || null, advance } }
function PillGroup({ label, options, value, onChange }) { return <div className="playbook-trainer__pillgroup"><span className="playbook-trainer__pillgroup-label">{label}</span><div className="playbook-trainer__pills" role="radiogroup" aria-label={label}>{options.map((opt) => <button key={String(opt.value)} type="button" role="radio" aria-checked={value === opt.value} className={`playbook-trainer__pill${value === opt.value ? ' is-selected' : ''}`} onClick={() => onChange(opt.value)}>{opt.label}</button>)}</div></div> }
function FieldBackground() { const lines = [60, 120, 180, 240]; const bands = [0, 120, 240]; const hashes = [30, 90, 150, 210, 270].flatMap((y) => { const row = []; for (let x = 24; x <= 456; x += 36) row.push([x, y]); return row }); return <svg className="playbook-trainer__field-bg" viewBox={`0 0 ${BOARD_W} ${CANVAS_H}`} aria-hidden="true"><rect width={CANVAS_W} height={CANVAS_H} className="playbook-trainer__field-turf" />{bands.map((y) => <rect key={y} y={y} width={CANVAS_W} height="60" className="playbook-trainer__field-band" />)}{lines.map((y) => <line key={y} x1="0" y1={y} x2={CANVAS_W} y2={y} className="playbook-trainer__field-yardline" />)}{hashes.map(([x, y]) => <line key={`${x}-${y}`} x1={x - 5} y1={y} x2={x + 5} y2={y} className="playbook-trainer__field-hash" />)}{lines.flatMap((y, i) => [<text key={`nl${y}`} x="9" y={y - 7} className="playbook-trainer__field-number">{(i + 1) * 10}</text>, <text key={`nr${y}`} x={CANVAS_W - 9} y={y - 7} textAnchor="end" className="playbook-trainer__field-number">{(i + 1) * 10}</text>])}<line x1={CANVAS_W + 1.5} y1="0" x2={CANVAS_W + 1.5} y2={CANVAS_H} className="playbook-trainer__field-trayline" /></svg> }
function Bubble({ bubble, editable, onDragStart }) { const isQb = bubble.type === 'QB'; return <g className={`playbook-trainer__bubble playbook-trainer__bubble--${bubble.type.toLowerCase()}${editable ? ' is-editable' : ''}`} transform={`translate(${bubble.x} ${bubble.y})`} onPointerDown={(e) => editable && onDragStart(e, bubble.id)}>{isQb ? <rect x="-13" y="-10" width="26" height="20" rx="2" /> : <circle r={bubble.type.startsWith('OL_') ? 11 : 14} />}<text dy=".35em">{isQb ? 'QB' : bubble.type.startsWith('OL_') ? '' : bubble.type}</text></g> }
function DiagramSvg({ diagram, editable = false, onChange }) {
  const svgRef = useRef(null), [activeLine, setActiveLine] = useState(null), [snap, setSnap] = useState(null), drag = useRef(null)
  const point = (event) => { const r = svgRef.current.getBoundingClientRect(); return { x: Math.max(0, Math.min(BOARD_W, (event.clientX - r.left) * BOARD_W / r.width)), y: Math.max(0, Math.min(CANVAS_H, (event.clientY - r.top) * CANVAS_H / r.height)) } }
  const snapPoint = (raw) => { const points = [...diagram.bubbles, ...diagram.lines.flatMap((line) => line.points.length ? [line.points[0], line.points.at(-1)] : [])]; const nearest = points.reduce((best, candidate) => { const d = Math.hypot(raw.x - candidate.x, raw.y - candidate.y); return d < best.d ? { candidate, d } : best }, { d: Infinity }); if (nearest.d <= SNAP_DISTANCE) { setSnap(nearest.candidate); return { x: nearest.candidate.x, y: nearest.candidate.y } } setSnap(null); return raw }
  const startDraw = (e) => { if (!editable || e.button !== 0) return; const p = snapPoint(point(e)); svgRef.current.setPointerCapture(e.pointerId); setActiveLine({ id: crypto.randomUUID(), points: [p] }) }
  const move = (e) => { if (!editable) return; const p = point(e); if (drag.current) { const next = { ...diagram, bubbles: diagram.bubbles.map((b) => b.id === drag.current ? { ...b, ...p } : b) }; onChange(next); return } if (activeLine) setActiveLine((line) => ({ ...line, points: [...line.points, snapPoint(p)] })) }
  const stop = (e) => { if (drag.current) { drag.current = null; setSnap(null) } if (activeLine?.points.length > 1) onChange({ ...diagram, lines: [...diagram.lines, activeLine] }); setActiveLine(null); setSnap(null); if (svgRef.current?.hasPointerCapture?.(e.pointerId)) svgRef.current.releasePointerCapture(e.pointerId) }
  const startDrag = (e, id) => { e.stopPropagation(); drag.current = id; svgRef.current.setPointerCapture(e.pointerId) }
  return <svg ref={svgRef} viewBox={`0 0 ${BOARD_W} ${CANVAS_H}`} className={`playbook-trainer__diagram${editable ? ' is-editable' : ''}`} onPointerDown={startDraw} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop} onContextMenu={(e) => e.preventDefault()}>{diagram.lines.map((line) => <path key={line.id} className="playbook-trainer__route" d={strokePath(line.points)} />)}{activeLine && <path className="playbook-trainer__route is-active" d={strokePath(activeLine.points)} />}{diagram.bubbles.map((bubble) => <Bubble key={bubble.id} bubble={bubble} editable={editable} onDragStart={startDrag} />)}{snap && <circle className="playbook-trainer__snap" cx={snap.x} cy={snap.y} r="5" />}</svg>
}
function DiagramBoard({ diagram, editable, onChange }) { return <div className="playbook-trainer__diagram-editor"><div className="playbook-trainer__canvas-wrap"><FieldBackground /><DiagramSvg diagram={diagram} editable={editable} onChange={onChange} /></div>{editable && <aside className="playbook-trainer__position-tray"><b>Personnel</b><span>Drag X · H · Y · Z onto the field. Routes snap to players and endpoints.</span></aside>}</div> }
function DiagramView({ diagram, className = '' }) { const value = normalDiagram(diagram); return value && <div className={`playbook-trainer__answer-diagram ${className}`}><DiagramBoard diagram={value} /></div> }
function Hud({ session, mastered, total }) { const accuracy = session.attempts ? Math.round(session.correct / session.attempts * 100) : null; return <div className="playbook-trainer__hud"><div className="playbook-trainer__hud-stat"><b>{accuracy === null ? '—' : `${accuracy}%`}</b><small>accuracy this session</small></div><div className="playbook-trainer__hud-stat"><b>{session.streak}</b><small>streak</small></div><div className="playbook-trainer__hud-stat"><b>{mastered}/{total}</b><small>mastered</small></div></div> }
function EmptyState({ children }) { return <p className="playbook-trainer__status">{children}</p> }
function PracticeTab({ deck, category, session, gradeAndAdvance }) { const pool = useMemo(() => category === 'all' ? deck : deck.filter((c) => c.category === category), [deck, category]); const drill = useDrillCard(pool); const [revealed, setRevealed] = useState(false); useEffect(() => setRevealed(false), [drill.current?.id]); return <><Hud session={session} mastered={pool.filter((c) => c.box === 5).length} total={pool.length} />{!pool.length ? <EmptyState>No cards in this category yet — add some in Manage.</EmptyState> : drill.current && <div className="playbook-trainer__card"><p className="playbook-trainer__card-name">{drill.current.prompt}</p>{tagsFor(drill.current).length > 0 && <div className="playbook-trainer__tags">{tagsFor(drill.current).map((t) => <i key={t}>{t}</i>)}</div>}{!revealed ? <button type="button" className="playbook-trainer__reveal-btn" onClick={() => setRevealed(true)}>Reveal answer</button> : <div className="playbook-trainer__reveal"><p className="playbook-trainer__answer-text">{drill.current.answerText}</p><DiagramView diagram={drill.current.answerDiagram} /><GradeRow onGrade={(gotIt) => gradeAndAdvance(drill, drill.current, gotIt)} /></div>}</div>}</> }
function GradeRow({ onGrade }) { return <div className="playbook-trainer__grade-row"><button type="button" className="playbook-trainer__grade-btn playbook-trainer__grade-btn--miss" onClick={() => onGrade(false)}>Missed it</button><button type="button" className="playbook-trainer__grade-btn playbook-trainer__grade-btn--got" onClick={() => onGrade(true)}>Got it</button></div> }
function DrawTab({ deck, category, session, gradeAndAdvance }) { const pool = useMemo(() => category === 'all' ? deck : deck.filter((c) => c.category === category), [deck, category]); const drawPool = useMemo(() => pool.filter((c) => normalDiagram(c.answerDiagram)), [pool]); const drill = useDrillCard(drawPool); const [comparing, setComparing] = useState(false), [drawing, setDrawing] = useState(createDiagram); useEffect(() => { setComparing(false); setDrawing(createDiagram()) }, [drill.current?.id]); const clear = () => setDrawing(createDiagram()); return <><Hud session={session} mastered={drawPool.filter((c) => c.box === 5).length} total={drawPool.length} />{pool.length - drawPool.length > 0 && <p className="playbook-trainer__note">{pool.length - drawPool.length} card{pool.length - drawPool.length === 1 ? '' : 's'} in this category don't have a saved diagram yet — add one in Manage to include them here.</p>}{!drawPool.length ? <EmptyState>No drawable cards in this category yet — add a diagram to a card in Manage.</EmptyState> : drill.current && <div className="playbook-trainer__card"><p className="playbook-trainer__card-name">{drill.current.prompt}</p><p className="playbook-trainer__draw-hint">Build the formation and draw it from memory.</p>{!comparing ? <><DiagramBoard diagram={drawing} editable onChange={setDrawing} /><div className="playbook-trainer__draw-actions"><button type="button" className="playbook-trainer__secondary-btn" onClick={clear}>Clear</button><button type="button" className="playbook-trainer__reveal-btn" onClick={() => setComparing(true)}>Compare to answer</button></div></> : <div className="playbook-trainer__reveal"><div className="playbook-trainer__compare-row"><div><span className="playbook-trainer__compare-label">Your drawing</span><DiagramView diagram={drawing} /></div><div><span className="playbook-trainer__compare-label">Answer</span><DiagramView diagram={drill.current.answerDiagram} /></div></div><p className="playbook-trainer__answer-text">{drill.current.answerText}</p><GradeRow onGrade={(gotIt) => gradeAndAdvance(drill, drill.current, gotIt)} /></div>}</div>}</> }
function emptyForm() { return { id: null, category: 'formation', name: '', side: '', variation: '', answerText: '', answerDiagram: createDiagram() } }
function CardForm({ form, setForm, onSave, onCancel }) { const ready = form.name.trim() && form.answerText.trim(); const diagram = normalDiagram(form.answerDiagram) || createDiagram(); return <div className="playbook-trainer__form"><label className="playbook-trainer__field"><span>Category</span><select value={form.category} onChange={(e) => setForm((f) => ({ ...f, category: e.target.value }))}>{CATEGORY_SELECT_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label><label className="playbook-trainer__field"><span>Name</span><input value={form.name} onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))} placeholder="e.g. Trips Right" /></label><PillGroup label="Side" options={SIDE_OPTIONS} value={form.side} onChange={(v) => setForm((f) => ({ ...f, side: v }))} /><label className="playbook-trainer__field"><span>Variation (optional)</span><input value={form.variation} onChange={(e) => setForm((f) => ({ ...f, variation: e.target.value }))} placeholder="e.g. vs 2x2" /></label><label className="playbook-trainer__field"><span>Answer / rule</span><textarea value={form.answerText} onChange={(e) => setForm((f) => ({ ...f, answerText: e.target.value }))} rows={4} /></label><div className="playbook-trainer__field"><span>Diagram</span><DiagramBoard diagram={diagram} editable onChange={(answerDiagram) => setForm((f) => ({ ...f, answerDiagram }))} /><div className="playbook-trainer__draw-actions"><button type="button" className="playbook-trainer__secondary-btn" onClick={() => setForm((f) => ({ ...f, answerDiagram: createDiagram() }))}>Clear routes & reset formation</button><button type="button" className="playbook-trainer__secondary-btn" onClick={() => setForm((f) => ({ ...f, answerDiagram: null }))}>Remove diagram</button></div></div><div className="playbook-trainer__form-actions"><button type="button" className="playbook-trainer__secondary-btn" onClick={onCancel}>Cancel</button><button type="button" className="playbook-trainer__reveal-btn" disabled={!ready} onClick={() => onSave({ ...form, answerDiagram: form.answerDiagram })}>Save</button></div></div> }
function ManageTab({ deck, category, onAdd, onEdit, onDelete, onResetDeck }) { const [form, setForm] = useState(null); const grouped = useMemo(() => { const list = category === 'all' ? deck : deck.filter((c) => c.category === category); return category !== 'all' ? [[category, list]] : CATEGORY_SELECT_OPTIONS.map((o) => [o.value, list.filter((c) => c.category === o.value)]).filter(([, cards]) => cards.length) }, [deck, category]); return <div className="playbook-trainer__manage"><div className="playbook-trainer__manage-toolbar"><button type="button" className="playbook-trainer__reveal-btn" onClick={() => setForm(emptyForm())}>+ Add card</button><button type="button" className="playbook-trainer__secondary-btn" onClick={onResetDeck}>Reset to example deck</button></div>{form && <CardForm form={form} setForm={setForm} onSave={(values) => { (form.id ? onEdit : onAdd)(values); setForm(null) }} onCancel={() => setForm(null)} />}{grouped.map(([cat, cards]) => <div className="playbook-trainer__manage-group" key={cat}><h2>{CATEGORY_SELECT_OPTIONS.find((o) => o.value === cat)?.label}</h2>{cards.map((card) => <div className="playbook-trainer__manage-row" key={card.id}><div className="playbook-trainer__manage-row-info"><span className="playbook-trainer__manage-row-name">{card.name}</span><span className="playbook-trainer__manage-row-box">Box {card.box}</span></div><div className="playbook-trainer__manage-row-actions"><button type="button" className="playbook-trainer__secondary-btn" onClick={() => setForm({ id: card.id, category: card.category, name: card.name, side: card.side || '', variation: card.variation || '', answerText: card.answerText, answerDiagram: normalDiagram(card.answerDiagram) || createDiagram() })}>Edit</button><button type="button" className="playbook-trainer__secondary-btn playbook-trainer__secondary-btn--danger" onClick={() => onDelete(card)}>Delete</button></div></div>)}</div>)}</div> }
export default function PlaybookTrainerPage() { const [deck, setDeck] = useState(loadDeck), [tab, setTab] = useState('practice'), [category, setCategory] = useState('all'), [session, setSession] = useState(blankSession); const gradeCard = useCallback((cardId, gotIt) => { setDeck((prev) => { const next = prev.map((c) => c.id !== cardId ? c : { ...c, box: gotIt ? Math.min(5, c.box + 1) : 1, attempts: c.attempts + 1, correct: c.correct + (gotIt ? 1 : 0) }); saveDeck(next); return next }); setSession((s) => { const streak = gotIt ? s.streak + 1 : 0; return { attempts: s.attempts + 1, correct: s.correct + (gotIt ? 1 : 0), streak, best: Math.max(s.best, streak) } }) }, []); const persist = (values, isEdit) => { const name = values.name.trim(), variation = values.variation.trim() || null; setDeck((prev) => { const card = { ...values, name, variation, side: values.side || null, prompt: buildPrompt(name, variation, values.side || null), answerText: values.answerText, answerDiagram: normalDiagram(values.answerDiagram) }; const next = isEdit ? prev.map((c) => c.id === card.id ? { ...c, ...card } : c) : [...prev, { ...card, id: crypto.randomUUID(), box: 1, attempts: 0, correct: 0 }]; saveDeck(next); return next }) }; const resetDeck = () => { if (!window.confirm('Reset to the example deck? This wipes all your saved cards and progress.')) return; const fresh = structuredClone(seed); saveDeck(fresh); setDeck(fresh); setSession(blankSession()) }; return <section className="playbook-trainer"><header className="playbook-trainer__header"><span className="playbook-trainer__eyebrow">PERSONAL / PLAYBOOK TRAINER</span><h1>If you can't draw the play, you don't know it.</h1><p>Drill your formations and pass concepts like flashcards, then draw them from memory.</p></header><div className="playbook-trainer__tabs" role="tablist">{[['practice', 'Practice'], ['draw', 'Draw'], ['manage', 'Manage']].map(([value, label]) => <button key={value} type="button" role="tab" aria-selected={tab === value} className={`playbook-trainer__tab${tab === value ? ' is-selected' : ''}`} onClick={() => setTab(value)}>{label}</button>)}</div><PillGroup label="Category" options={CATEGORIES} value={category} onChange={setCategory} /><div role="tabpanel">{tab === 'practice' && <PracticeTab deck={deck} category={category} session={session} gradeAndAdvance={(drill, card, gotIt) => { gradeCard(card.id, gotIt); drill.advance(card.id) }} />}{tab === 'draw' && <DrawTab deck={deck} category={category} session={session} gradeAndAdvance={(drill, card, gotIt) => { gradeCard(card.id, gotIt); drill.advance(card.id) }} />}{tab === 'manage' && <ManageTab deck={deck} category={category} onAdd={(v) => persist(v, false)} onEdit={(v) => persist(v, true)} onDelete={(card) => { if (window.confirm(`Delete "${card.name}"? This cannot be undone.`)) setDeck((prev) => { const next = prev.filter((c) => c.id !== card.id); saveDeck(next); return next }) }} onResetDeck={resetDeck} />}</div></section> }
